# Exemplary Use of the Factor Forest

# Exemplary data: Answers to 50 BIG 5 personality items 1369 participants
# retrieved from https://openpsychometrics.org/_rawdata/ ("randombumber.zip": 
# last updated 11/14/2018)

# read data and get rid of random numbers generated by participants:

data <- read.csv("data.csv")[,-(1:21)]

# download all necessary files from https://osf.io/mvrau/:

# use "Analysis Script.R"

# load packages

library(mlr)
library(psych)
library(ineq)
library(BBmisc)
library(ddpcr)

# source scripts for helper functions

source("xgb-functions.R")
source("CD_approach.R")
source("factor.forest.R")

# load pre-trained model

xgb <- readRDS(file = "tunedxgb.rds")

# use factor.forest function to predict the number of factors

factor.forest(newdata = data, mod = xgb) # predicting the number of factors can take some time




